version: '3'
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport:11
    container_name: teleport
    hostname: teleport.shubhamtatvamasi.com
    ports:
      - "3022:3022" # SSH port
      - "3023:3023" # authenticate with proxy
      - "3025:3025" # authentication service
      - "443:443" # teleport Dashboard
    volumes:
      - ./config:/etc/teleport
      - teleport_data:/var/lib/teleport

volumes:
  teleport_data:
