version: '3'
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport:11
    container_name: teleport
    restart: unless-stopped
    hostname: teleport.shubhamtatvamasi.com
    ports:
      - "3022:3022" # SSH port
      - "3023:3023" # authenticate with proxy
      - "3024:3024" # authenticate listening address
      - "3025:3025" # authentication service
      - "3026:3026" # kubernetes service
      - "3036:3036" # mysql service
      - "443:443" # teleport Dashboard
    volumes:
      - ./config:/etc/teleport
      - ./teleport:/var/lib/teleport
