version: v3
teleport:
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.shubhamtatvamasi.com
  authentication:
    type: "local"
    local_auth: true
    second_factor: "otp"
ssh_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3022
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  listen_addr: 0.0.0.0:3023
  tunnel_listen_addr: 0.0.0.0:3024
  kube_listen_addr: 0.0.0.0:3026
  mysql_listen_addr: 0.0.0.0:3036
  public_addr: teleport.shubhamtatvamasi.com:443
  https_keypairs:
    - key_file: /var/lib/teleport/key.pem
      cert_file: /var/lib/teleport/cert.pem
  # acme:
  #   enabled: "yes"
  #   email: shubhamtatvamasi@gmail.com
